name: Build documentation

on:
  push:
    branches:
      - next
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'release') || (github.event_name == 'workflow_dispatch') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download
        run: npm i @discordjs/ts-docgen typedoc-plugin-djs-links

      - name: Build
        run: npm run build:docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./docs
          publish_branch: docs
          destination_dir: ./docs/
          keep_files: true

  deploy_next:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download
        run: npm i @discordjs/ts-docgen typedoc-plugin-djs-links

      - name: Build
        run: npm run build:next-docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./docs
          publish_branch: docs
          destination_dir: ./docs/
          keep_files: true
