name: Labeler
on:
  pull_request_review:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - '.github/labels.yml'
jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v3
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
  labelWhenApproved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
    - name: Label when approved
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "2"
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ADD_LABEL: "s: approved"
        REMOVE_LABEL: "s: awaiting review"