name: PR Automation

on:
  pull_request_target:
    types:
      - opened

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewers
        uses: kentaro-m/auto-assign-action@v1.1.2
