name: "Release"

on: [ workflow_dispatch ]

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: npm

      - name: Install
        run: npm install --save-dev discord-api-types @discordjs/rest ms discord.js @babel/cli @babel/core @babel/preset-env @babel/preset-typescript babel-plugin-add-module-exports typescript @types/node

      - name: build
        run: npm run build

      - name: publish
        run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
