name: Testing
on: [push, pull_request]
jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v12
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install dependencies
        run: npm i

      - name: Run ESLint
        run: npm run test
        id: eslint
        continue-on-error: true

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Success
        if: ${{ steps.eslint.outcome == 'success' }}
        uses: omio-labs/pr-reviewer-bot@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EVENT_TYPE: APPROVE
          MESSAGE: 'Everything is fine.'
      - name: Failure
        if: ${{ steps.eslint.outcome != 'success' }}
        uses: golfzaptw/action-auto-reviews-from-branches@master
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EVENT_TYPE: REQUEST_CHANGES
          MESSAGE: 'ESLint found errors. Please correct them. ${{ github.job }}'